---
output:
  bookdown::pdf_document2:
    toc: False
---

<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
  }

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE)
```

```{r}
library("AER")
library(tidyverse)
data(Fatalities)

sum(is.na(Fatalities))

```

```{r}
data = Fatalities %>% 
  mutate(fatal_rate = fatal/pop*10000)

```

```{r}
library("directlabels")
#data %>% 
#  ggplot(aes(x = year, y  = fatal_rate, group = state, color = state)) +
#  geom_line()+
#  facet_wrap(state~.)+
#  theme(legend.position="none")
#  #geom_dl(aes(label = state), method = list(dl.combine("first.points", "last.points")))
```

```{r}
data %>% 
  group_by(state) %>% 
  summarise(yes = sum(jail == "yes"), no = sum(jail == "no")) %>% 
  filter(yes!=7 & yes != 0 | is.na(yes))

data %>% 
  group_by(state) %>% 
  summarise(yes = sum(jail == "yes"), no = sum(jail == "no")) %>% 
  filter(yes!=7 & yes != 0 | is.na(yes)) %>% 
  select(state)

state_1 <- c('ca', 'ct', 'nv', 'oh', 'or', 'sc', 'ut')

data %>% 
  filter(state %in% state_1) %>% 
  ggplot(aes(x = year, y  = fatal_rate, group = state)) +
  geom_line()+
  geom_point(aes(shape = jail), size = 3)+
  scale_shape_manual(values=c(5, 17))+
  geom_dl(aes(label = state), method = list("last.points")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  labs(y = "Fatality Rate", x = "Year")
  
```

Treatment selection may be confounded with patient characteristics related to the outcome. 

# map 
```{r}
library(maps)
library(ggplot2)
library(openintro)
library(dplyr)

states_map <- map_data("state") %>% 
  mutate(state = str_to_lower(state2abbr(region)))

data_2 <- data %>% 
  left_join(states_map, by="state")

data_2 %>% 
  ggplot(aes(long, lat, group = group))+
  geom_polygon(aes(fill = jail, frame = year), color = "white")+
  scale_fill_viridis_d()+
  facet_wrap(~year)

data_2 %>% 
  ggplot(aes(long, lat, group = group))+
  geom_polygon(aes(fill = fatal_rate, frame = year), color = "white")+
  scale_fill_viridis_c()+
  facet_wrap(~year)
```

# model
```{r}
library(wfe)

d1= Fatalities %>% 
  mutate(fatal_rate = fatal/pop*10000)

d1$jail = as.integer(ifelse(d1$jail == 'yes', 1, 0))
d1[d1$state == "ca" & d1$year == "1988",]$jail = 0


f = pwfe(~ jail + spirits + unemp + income + beertax + drinkage + dry + youngdrivers + miles + breath + pop + gsp , data = d1, treat = "jail", outcome = "fatal_rate", unit.index = "state", time.index = "year", method = "unit", within.unit = TRUE, qoi = "ate", hetero.se=TRUE, auto.se=TRUE)

summary(f)
```

